export { default as AppointmentsIcon } from "./AppointmentsIcon";
export { default as DashboardIcon } from "./DashboardIcon";
export { default as DoctorsIcon } from "./DoctorsIcon";
export { default as FamilyIcon } from "./FamilyIcon";
export { default as HealthIcon } from "./HealthIcon";
export { default as LogoutIcon } from "./LogoutIcon";
export { default as PackagesIcon } from "./PackagesIcon";
export { default as SettingsIcon } from "./SettingsIcon";
export { default as PrescriptionsIcon } from "./PrescriptionsIcon";
