export const LOG_OUT = "LOG_OUT";

export const USERS_DATA_LOADING = "USERS_DATA_LOADING";
export const USERS_DATA_SUCCESS = "USERS_DATA_SUCCESS";
export const USERS_DATA_FAILURE = "USERS_DATA_FAILURE";

// SHADY TYPES
export const PATIENT_GET_DOCTORS_LOADING = "PATIENT_GET_DOCTORS_LOADING";
export const PATIENT_GET_DOCTORS_SUCCESS = "PATIENT_GET_DOCTORS_SUCCESS";
export const PATIENT_GET_DOCTORS_FAILURE = "PATIENT_GET_DOCTORS_FAILURE";

export const PATIENT_SEARCH_DOCTORS_FAILURE = "PATIENT_SEARCH_DOCTORS_FAILURE";

export const PATIENT_FILTER_DOCTORS_FAILURE = "PATIENT_FILTER_DOCTORS_FAILURE";

export const ALL_SPECILATIES_LOADING = "ALL_SPECILATIES_LOADING";
export const ALL_SPECILATIES_SUCCESS = "ALL_SPECILATIES_SUCCESS";
export const ALL_SPECILATIES_FAILURE = "ALL_SPECILATIES_FAILURE";

export const SET_DOCTOR_CARD_COORDS = "SET_DOCTOR_CARD_COORDS";

// ZEINA TYPES
export const DOCTOR_DATA_LOADING = "DOCTOR_DATA_LOADING";
export const DOCTOR_DATA_SUCCESS = "DOCTOR_DATA_SUCCESS";
export const DOCTOR_DATA_FAILURE = "DOCTOR_DATA_FAILURE";

//// NEVEEN TYPES

export const PATIENTS_DATA_LOADING = "PATIENTS_DATA_LOADING";
export const PATIENTS_DATA_SUCCESS = "PATIENTS_DATA_SUCCESS";
export const PATIENTS_DATA_FAILURE = "PATIENTS_DATA_FAILURE";

export const PATIENT_INFO_DATA_LOADING = "PATIENT_INFO_DATA_LOADING";
export const PATIENT_INFO_DATA_SUCCESS = "PATIENT_INFO_DATA_SUCCESS";
export const PATIENT_INFO_DATA_FAILURE = "PATIENT_INFO_DATA_FAILURE";

export const UPCOMING_PATIENTS_DATA_LOADING = "UPCOMING_PATIENTS_DATA_LOADING";
export const UPCOMING_PATIENTS_DATA_SUCCESS = "UPCOMING_PATIENTS_DATA_SUCCESS";
export const UPCOMING_PATIENTS_DATA_FAILURE = "UPCOMING_PATIENTS_DATA_FAILURE";

export const SEARCH_PATIENT_LOADING = "SEARCH_PATIENT_LOADING";
export const SEARCH_PATIENT_SUCCESS = "SEARCH_PATIENT_SUCCESS";
export const SEARCH_PATIENT_FAILURE = "SEARCH_PATIENT_FAILURE";

export const DOCTOR_SETTINGS_DATA_LOADING = "DOCTOR_SETTINGS_DATA_LOADING";
export const DOCTOR_SETTINGS_DATA_SUCCESS = "DOCTOR_SETTINGS_DATA_SUCCESS";
export const DOCTOR_SETTINGS_DATA_FAILURE = "DOCTOR_SETTINGS_DATA_FAILURE";

export const EDIT_DOCTOR_SETTINGS_DATA_LOADING =
  "EDIT_DOCTOR_SETTINGS_DATA_LOADING";
export const EDIT_DOCTOR_SETTINGS_DATA_SUCCESS =
  "EDIT_DOCTOR_SETTINGS_DATA_SUCCESS";
export const EDIT_DOCTOR_SETTINGS_DATA_FAILURE =
  "EDIT_DOCTOR_SETTINGS_DATA_FAILURE";

//// MOSTAFA TYPES
export const GET_APPOINTMENTS_DATA_LOADING = "APPOINTMENTS_DATA_LOADING";
export const GET_APPOINTMENTS_DATA_SUCCESS = "APPOINTMENTS_DATA_SUCCESS";
export const GET_APPOINTMENTS_DATA_FAILURE = "APPOINTMENTS_DATA_FAILURE";

export const POST_APPOINTMENT_DATA_LOADING = "POST_APPOINTMENT_DATA_LOADING";
export const POST_APPOINTMENT_DATA_SUCCESS = "POST_APPOINTMENT_DATA_SUCCESS";
export const POST_APPOINTMENT_DATA_FAILURE = "POST_APPOINTMENT_DATA_FAILURE";

export const PUT_APPOINTMENT_DATA_LOADING = "PUT_APPOINTMENT_DATA_LOADING";
export const PUT_APPOINTMENT_DATA_SUCCESS = "PUT_APPOINTMENT_DATA_SUCCESS";
export const PUT_APPOINTMENT_DATA_FAILURE = "PUT_APPOINTMENT_DATA_FAILURE";

export const DELETE_APPOINTMENT_DATA_LOADING =
  "DELETE_APPOINTMENT_DATA_LOADING";
export const DELETE_APPOINTMENT_DATA_SUCCESS =
  "DELETE_APPOINTMENT_DATA_SUCCESS";
export const DELETE_APPOINTMENT_DATA_FAILURE =
  "DELETE_APPOINTMENT_DATA_FAILURE";

export const ADD_FAMILYMEMBER_DATA_LOADING = "ADD_FAMILYMEMBER_DATA_LOADING";
export const ADD_FAMILYMEMBER_DATA_SUCCESS = "ADD_FAMILYMEMBER_DATA_SUCCESS";
export const ADD_FAMILYMEMBER_DATA_FAILURE = "ADD_FAMILYMEMBER_DATA_FAILURE";

export const GET_FAMILYMEMBERS_DATA_LOADING = "GET_FAMILYMEMBERS_DATA_LOADING";
export const GET_FAMILYMEMBERS_DATA_SUCCESS = "GET_FAMILYMEMBERS_DATA_SUCCESS";
export const GET_FAMILYMEMBERS_DATA_FAILURE = "GET_FAMILYMEMBERS_DATA_FAILURE";

// YOUSSEF TYPES
export const PRESCRIPTIONS_DATA_LOADING = "PRESCRIPTIONS_DATA_LOADING";
export const PRESCRIPTIONS_DATA_SUCCESS = "PRESCRIPTIONS_DATA_SUCCESS";
export const PRESCRIPTIONS_DATA_FAILURE = "PRESCRIPTIONS_DATA_FAILURE";

export const PRESCRIPTIONS_DETAILS_DATA_LOADING =
  "PRESCRIPTIONS_DETAILS_DATA_LOADING";
export const PRESCRIPTIONS_DETAILS_DATA_SUCCESS =
  "PRESCRIPTIONS_DETAILS_DATA_SUCCESS";
export const PRESCRIPTIONS_DETAILS_DATA_FAILURE =
  "PRESCRIPTIONS_DETAILS_DATA_FAILURE";

// SEIF TYPES
export const PACKAGES_DATA_LOADING = "PACKAGES_DATA_LOADING";
export const PACKAGES_DATA_SUCCESS = "PACKAGES_DATA_SUCCESS";
export const PACKAGES_DATA_FAILURE = "PACKAGES_DATA_FAILURE";

export const UPDATED_PACKAGE_DATA_LOADING = "UPDATED_PACKAGE_DATA_LOADING";
export const UPDATED_PACKAGE_DATA_SUCCESS = "UPDATED_PACKAGE_DATA_SUCCESS";
export const UPDATED_PACKAGE_DATA_FAILURE = "UPDATED_PACKAGE_DATA_FAILURE";

export const CREATED_PACKAGE_DATA_LOADING = "CREATED_PACKAGE_DATA_LOADING";
export const CREATED_PACKAGE_DATA_SUCCESS = "CREATED_PACKAGE_DATA_SUCCESS";
export const CREATED_PACKAGE_DATA_FAILURE = "CREATED_PACKAGE_DATA_FAILURE";

export const DELETING_PACKAGE_DATA_LOADING = "DELETING_PACKAGE_DATA_LOADING";
export const DELETING_PACKAGE_DATA_SUCCESS = "DELETING_PACKAGE_DATA_SUCCESS";
export const DELETING_PACKAGE_DATA_FAILURE = "DELETING_PACKAGE_DATA_FAILURE";

export const ALL_ADMINS_DATA_LOADING = "ALL_ADMINS_DATA_LOADING";
export const ALL_ADMINS_DATA_SUCCESS = "ALL_ADMINS_DATA_SUCCESS";
export const ALL_ADMINS_DATA_FAILURE = "ALL_ADMINS_DATA_FAILURE";

export const CREATED_ADMIN_DATA_LOADING = "CREATED_ADMIN_DATA_LOADING";
export const CREATED_ADMIN_DATA_SUCCESS = "CREATED_ADMIN_DATA_SUCCESS";
export const CREATED_ADMIN_DATA_FAILURE = "CREATED_ADMIN_DATA_FAILURE";

export const DELETED_ADMIN_DATA_LOADING = "DELETED_ADMIN_DATA_LOADING";
export const DELETED_ADMIN_DATA_SUCCESS = "DELETED_ADMIN_DATA_SUCCESS";
export const DELETED_ADMIN_DATA_FAILURE = "DELETED_ADMIN_DATA_FAILURE";

export const ADMIN_DOCTORS_DATA_LOADING = "ADMIN_DOCTORS_DATA_LOADING";
export const ADMIN_DOCTORS_DATA_SUCCESS = "ADMIN_DOCTORS_DATA_SUCCESS";
export const ADMIN_DOCTORS_DATA_FAILURE = "ADMIN_DOCTORS_DATA_FAILURE";

export const ADMIN_PATIENTS_DATA_LOADING = "ADMIN_PATIENTS_DATA_LOADING";
export const ADMIN_PATIENTS_DATA_SUCCESS = "ADMIN_PATIENTS_DATA_SUCCESS";
export const ADMIN_PATIENTS_DATA_FAILURE = "ADMIN_PATIENTS_DATA_FAILURE";

export const DELETE_DOCTOR_DATA_LOADING = "DELETE_DOCTOR_DATA_LOADING";
export const DELETE_DOCTOR_DATA_SUCCESS = "DELETE_DOCTOR_DATA_SUCCESS";
export const DELETE_DOCTOR_DATA_FAILURE = "DELETE_DOCTOR_DATA_FAILURE";

export const DELETE_PATIENT_DATA_LOADING = "DELETE_PATIENT_DATA_LOADING";
export const DELETE_PATIENT_DATA_SUCCESS = "DELETE_PATIENT_DATA_SUCCESS";
export const DELETE_PATIENT_DATA_FAILURE = "DELETE_PATIENT_DATA_FAILURE";

export const GET_CONTRACTS_DATA_LOADING = "GET_CONTRACTS_DATA_LOADING";
export const GET_CONTRACTS_DATA_SUCCESS = "GET_CONTRACTS_DATA_SUCCESS";
export const GET_CONTRACTS_DATA_FAILURE = "GET_CONTRACTS_DATA_FAILURE";

export const VIEW_PACKAGES_DATA_LOADING = "VIEW_PACKAGES_DATA_LOADING";
export const VIEW_PACKAGES_DATA_SUCCESS = "VIEW_PACKAGES_DATA_SUCCESS";
export const VIEW_PACKAGES_DATA_FAILURE = "VIEW_PACKAGES_DATA_FAILURE";

export const UNSUBSCRIBE_FROM_PACKAGE_DATA_LOADING = "UNSUBSCRIBE_FROM_PACKAGE_DATA_LOADING";
export const UNSUBSCRIBE_FROM_PACKAGE_DATA_SUCCESS = "UNSUBSCRIBE_FROM_PACKAGE_DATA_SUCCESS";
export const UNSUBSCRIBE_FROM_PACKAGE_DATA_FAILURE = "UNSUBSCRIBE_FROM_PACKAGE_DATA_FAILURE";


export const VIEW_SUBSCRIBED_PACKAGE_FOR_FAMILY_MEMBER_DATA_LOADING = "VIEW_SUBSCRIBED_PACKAGE_FOR_FAMILY_MEMBER_DATA_LOADING";
export const VIEW_SUBSCRIBED_PACKAGE_FOR_FAMILY_MEMBER_DATA_SUCCESS = "VIEW_SUBSCRIBED_PACKAGE_FOR_FAMILY_MEMBER_DATA_SUCCESS";
export const VIEW_SUBSCRIBED_PACKAGE_FOR_FAMILY_MEMBER_DATA_FAILURE = "VIEW_SUBSCRIBED_PACKAGE_FOR_FAMILY_MEMBER_DATA_FAILURE";

export const UNSUBSCRIBE_FROM_PACKAGE_FOR_FAMILY_DATA_LOADING = "UNSUBSCRIBE_FROM_PACKAGE_FOR_FAMILY_DATA_LOADING";
export const UNSUBSCRIBE_FROM_PACKAGE_FOR_FAMILY_DATA_SUCCESS = "UNSUBSCRIBE_FROM_PACKAGE_FOR_FAMILY_DATA_SUCCESS";
export const UNSUBSCRIBE_FROM_PACKAGE_FOR_FAMILY_DATA_FAILURE = "UNSUBSCRIBE_FROM_PACKAGE_FOR_FAMILY_DATA_FAILURE";

export const VIEW_PACKAGE_PRICE_DATA_LOADING = "VIEW_PACKAGE_PRICE_DATA_LOADING";
export const VIEW_PACKAGE_PRICE_DATA_SUCCESS = "VIEW_PACKAGE_PRICE_DATA_SUCCESS";
export const VIEW_PACKAGE_PRICE_DATA_FAILURE = "VIEW_PACKAGE_PRICE_DATA_FAILURE";
