export const LOG_OUT = "LOG_OUT";

export const USERS_DATA_LOADING = "USERS_DATA_LOADING";
export const USERS_DATA_SUCCESS = "USERS_DATA_SUCCESS";
export const USERS_DATA_FAILURE = "USERS_DATA_FAILURE";

// SHADY TYPES
export const PATIENT_GET_DOCTORS_LOADING = "PATIENT_GET_DOCTORS_LOADING";
export const PATIENT_GET_DOCTORS_SUCCESS = "PATIENT_GET_DOCTORS_SUCCESS";
export const PATIENT_GET_DOCTORS_FAILURE = "PATIENT_GET_DOCTORS_FAILURE";

export const PATIENT_SEARCH_DOCTORS_FAILURE = "PATIENT_GET_DOCTORS_FAILURE";

export const ALL_SPECILATIES_LOADING = "ALL_SPECILATIES_LOADING";
export const ALL_SPECILATIES_SUCCESS = "ALL_SPECILATIES_SUCCESS";
export const ALL_SPECILATIES_FAILURE = "ALL_SPECILATIES_FAILURE";

// ZEINA TYPES
export const DOCTOR_DATA_LOADING = "DOCTOR_DATA_LOADING";
export const DOCTOR_DATA_SUCCESS = "DOCTOR_DATA_SUCCESS";
export const DOCTOR_DATA_FAILURE = "DOCTOR_DATA_FAILURE";

