export const LOG_OUT = "LOG_OUT";

export const USERS_DATA_LOADING = "USERS_DATA_LOADING";
export const USERS_DATA_SUCCESS = "USERS_DATA_SUCCESS";
export const USERS_DATA_FAILURE = "USERS_DATA_FAILURE";

//// NEVEEN TYPES

export const PATIENTS_DATA_LOADING = "PATIENTS_DATA_LOADING";
export const PATIENTS_DATA_SUCCESS = "PATIENTS_DATA_SUCCESS";
export const PATIENTS_DATA_FAILURE = "PATIENTS_DATA_FAILURE";

export const PATIENT_INFO_DATA_LOADING = "PATIENT_INFO_DATA_LOADING";
export const PATIENT_INFO_DATA_SUCCESS = "PATIENT_INFO_DATA_SUCCESS";
export const PATIENT_INFO_DATA_FAILURE = "PATIENT_INFO_DATA_FAILURE";

export const UPCOMING_PATIENTS_DATA_LOADING = "UPCOMING_PATIENTS_DATA_LOADING";
export const UPCOMING_PATIENTS_DATA_SUCCESS = "UPCOMING_PATIENTS_DATA_SUCCESS";
export const UPCOMING_PATIENTS_DATA_FAILURE = "UPCOMING_PATIENTS_DATA_FAILURE";

export const SEARCH_PATIENT_LOADING = "SEARCH_PATIENT_LOADING";
export const SEARCH_PATIENT_SUCCESS = "SEARCH_PATIENT_SUCCESS";
export const SEARCH_PATIENT_FAILURE = "SEARCH_PATIENT_FAILURE";

export const DOCTOR_SETTINGS_DATA_LOADING = "DOCTOR_SETTINGS_DATA_LOADING";
export const DOCTOR_SETTINGS_DATA_SUCCESS = "DOCTOR_SETTINGS_DATA_SUCCESS";
export const DOCTOR_SETTINGS_DATA_FAILURE = "DOCTOR_SETTINGS_DATA_FAILURE";

export const EDIT_DOCTOR_SETTINGS_DATA_LOADING = "EDIT_DOCTOR_SETTINGS_DATA_LOADING";
export const EDIT_DOCTOR_SETTINGS_DATA_SUCCESS = "EDIT_DOCTOR_SETTINGS_DATA_SUCCESS";
export const EDIT_DOCTOR_SETTINGS_DATA_FAILURE = "EDIT_DOCTOR_SETTINGS_DATA_FAILURE";

//// MOSTAFA TYPES
export const GET_APPOINTMENTS_DATA_LOADING = "APPOINTMENTS_DATA_LOADING";
export const GET_APPOINTMENTS_DATA_SUCCESS = "APPOINTMENTS_DATA_SUCCESS";
export const GET_APPOINTMENTS_DATA_FAILURE = "APPOINTMENTS_DATA_FAILURE";

export const POST_APPOINTMENT_DATA_LOADING = "POST_APPOINTMENT_DATA_LOADING";
export const POST_APPOINTMENT_DATA_SUCCESS = "POST_APPOINTMENT_DATA_SUCCESS";
export const POST_APPOINTMENT_DATA_FAILURE = "POST_APPOINTMENT_DATA_FAILURE";

export const PUT_APPOINTMENT_DATA_LOADING = "PUT_APPOINTMENT_DATA_LOADING";
export const PUT_APPOINTMENT_DATA_SUCCESS = "PUT_APPOINTMENT_DATA_SUCCESS";
export const PUT_APPOINTMENT_DATA_FAILURE = "PUT_APPOINTMENT_DATA_FAILURE";

export const DELETE_APPOINTMENT_DATA_LOADING = "DELETE_APPOINTMENT_DATA_LOADING";
export const DELETE_APPOINTMENT_DATA_SUCCESS = "DELETE_APPOINTMENT_DATA_SUCCESS";
export const DELETE_APPOINTMENT_DATA_FAILURE = "DELETE_APPOINTMENT_DATA_FAILURE";

export const ADD_FAMILYMEMBER_DATA_LOADING = "ADD_FAMILYMEMBER_DATA_LOADING";
export const ADD_FAMILYMEMBER_DATA_SUCCESS = "ADD_FAMILYMEMBER_DATA_SUCCESS";
export const ADD_FAMILYMEMBER_DATA_FAILURE = "ADD_FAMILYMEMBER_DATA_FAILURE";

export const GET_FAMILYMEMBERS_DATA_LOADING = "GET_FAMILYMEMBERS_DATA_LOADING";
export const GET_FAMILYMEMBERS_DATA_SUCCESS = "GET_FAMILYMEMBERS_DATA_SUCCESS";
export const GET_FAMILYMEMBERS_DATA_FAILURE = "GET_FAMILYMEMBERS_DATA_FAILURE";
