export const LOG_OUT = "LOG_OUT";

export const USERS_DATA_LOADING = "USERS_DATA_LOADING";
export const USERS_DATA_SUCCESS = "USERS_DATA_SUCCESS";
export const USERS_DATA_FAILURE = "USERS_DATA_FAILURE";

// SHADY TYPES
export const ALL_SPECILATIES_LOADING = "ALL_SPECILATIES_LOADING";
export const ALL_SPECILATIES_SUCCESS = "ALL_SPECILATIES_SUCCESS";
export const ALL_SPECILATIES_FAILURE = "ALL_SPECILATIES_FAILURE";

export const ALL_MEDICINAL_USES_LOADING = "ALL_MEDICINAL_USES_LOADING";
export const ALL_MEDICINAL_USES_SUCCESS = "ALL_MEDICINAL_USES_SUCCESS";
export const ALL_MEDICINAL_USES_FAILURE = "ALL_MEDICINAL_USES_FAILURE";

// ZEINA TYPES
export const PHARMACIST_DATA_LOADING = "PHARMACIST_DATA_LOADING";
export const PHARMACIST_DATA_SUCCESS = "PHARMACIST_DATA_SUCCESS";
export const PHARMACIST_DATA_FAILURE = "PHARMACIST_DATA_FAILURE";

export const PATIENT_MEDICINE_DATA_LOADING = "PATIENT_MEDICINE_DATA_LOADING";
export const PATIENT_MEDICINE_DATA_SUCCESS = "PATIENT_MEDICINE_DATA_SUCCESS";
export const PATIENT_MEDICINE_DATA_FAILURE = "PATIENT_MEDICINE_DATA_FAILURE";

//// NEVEEN TYPES
export const PATIENTS_DATA_LOADING = "PATIENTS_DATA_LOADING";
export const PATIENTS_DATA_SUCCESS = "PATIENTS_DATA_SUCCESS";
export const PATIENTS_DATA_FAILURE = "PATIENTS_DATA_FAILURE";

export const PATIENT_INFO_DATA_LOADING = "PATIENT_INFO_DATA_LOADING";
export const PATIENT_INFO_DATA_SUCCESS = "PATIENT_INFO_DATA_SUCCESS";
export const PATIENT_INFO_DATA_FAILURE = "PATIENT_INFO_DATA_FAILURE";

// SEIF TYPES
export const ALL_ADMINS_DATA_LOADING = "ALL_ADMINS_DATA_LOADING";
export const ALL_ADMINS_DATA_SUCCESS = "ALL_ADMINS_DATA_SUCCESS";
export const ALL_ADMINS_DATA_FAILURE = "ALL_ADMINS_DATA_FAILURE";

export const CREATED_ADMIN_DATA_LOADING = "CREATED_ADMIN_DATA_LOADING";
export const CREATED_ADMIN_DATA_SUCCESS = "CREATED_ADMIN_DATA_SUCCESS";
export const CREATED_ADMIN_DATA_FAILURE = "CREATED_ADMIN_DATA_FAILURE";

export const DELETED_ADMIN_DATA_LOADING = "DELETED_ADMIN_DATA_LOADING";
export const DELETED_ADMIN_DATA_SUCCESS = "DELETED_ADMIN_DATA_SUCCESS";
export const DELETED_ADMIN_DATA_FAILURE = "DELETED_ADMIN_DATA_FAILURE";

export const ADMIN_PHARMACISTS_DATA_LOADING = "ADMIN_PHARMACISTS_DATA_LOADING";
export const ADMIN_PHARMACISTS_DATA_SUCCESS = "ADMIN_PHARMACISTS_DATA_SUCCESS";
export const ADMIN_PHARMACISTS_DATA_FAILURE = "ADMIN_PHARMACISTS_DATA_FAILURE";

export const ADMIN_PATIENTS_DATA_LOADING = "ADMIN_PATIENTS_DATA_LOADING";
export const ADMIN_PATIENTS_DATA_SUCCESS = "ADMIN_PATIENTS_DATA_SUCCESS";
export const ADMIN_PATIENTS_DATA_FAILURE = "ADMIN_PATIENTS_DATA_FAILURE";

export const DELETE_PHARMACIST_DATA_LOADING = "DELETE_PHARMACIST_DATA_LOADING";
export const DELETE_PHARMACIST_DATA_SUCCESS = "DELETE_PHARMACIST_DATA_SUCCESS";
export const DELETE_PHARMACIST_DATA_FAILURE = "DELETE_PHARMACIST_DATA_FAILURE";

export const DELETE_PATIENT_DATA_LOADING = "DELETE_PATIENT_DATA_LOADING";
export const DELETE_PATIENT_DATA_SUCCESS = "DELETE_PATIENT_DATA_SUCCESS";
export const DELETE_PATIENT_DATA_FAILURE = "DELETE_PATIENT_DATA_FAILURE";

export const GET_CART = "GET_CART";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const CANCEL_ORDER = "CANCEL_ORDER";

export const GET_CONTRACTS_DATA_LOADING = "GET_CONTRACTS_DATA_LOADING";
export const GET_CONTRACTS_DATA_SUCCESS = "GET_CONTRACTS_DATA_SUCCESS";
export const GET_CONTRACTS_DATA_FAILURE = "GET_CONTRACTS_DATA_FAILURE";

